### ISSUE TITLE
mingw32-make !error on Win10

### ISSUE THREAD

**Issue by macaddr** [Ultimaker/cura-build#44] opened 2016-03-11 09:01 UTC
evn；win10 64-bit
mingw64
python3.4
pyqt5.5 for python3.4
i set all as README
but
D:\cura-build-2.1\build>mingw32-make
[ 12%] Built target Protobuf
[ 12%] Built target Python
[ 12%] Built target Sip
[ 14%] Performing update step for 'Arcus'

**\* Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <Administrator@AlmostSrinagar.(none)>) not allowed
Cannot save the current index state
CMake Error at D:/cura-build-2.1/build/Arcus-prefix/tmp/Arcus-gitupdate.cmake:83 (message):
  Failed to stash changes

CMakeFiles\Arcus.dir\build.make:93: recipe for target 'Arcus-prefix/src/Arcus-stamp/Arcus-update' failed
mingw32-make[2]: **\* [Arcus-prefix/src/Arcus-stamp/Arcus-update] Error 1
CMakeFiles\Makefile2:164: recipe for target 'CMakeFiles/Arcus.dir/all' failed
mingw32-make[1]: **\* [CMakeFiles/Arcus.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make: **\* [all] Error 2

D:\cura-build-2.1\build>

**Comment by Ghostkeeper** [comment] 2016-03-11 11:17
I think this is the remote throttling anonymous pulls. Try running `git config --local user.email "you@example.com" && git config --local user.name "Your Name"` inside the cura-build directory.

**Comment by macaddr** [comment] 2016-03-11 11:53
@Ghostkeeper 
3qs a lot
i meet  a new 

E:\test\cura-build\build>mingw32-make
[ 12%] Built target Protobuf
[ 12%] Built target Python
[ 12%] Built target Sip
[ 14%] Performing update step for 'Arcus'
Current branch HEAD is up to date.
[ 15%] Performing configure step for 'Arcus'
-- Configuring done
-- Generating done
-- Build files have been written to: E:/test/cura-build/build/Arcus-prefix/src/Arcus-build
[ 17%] Performing build step for 'Arcus'
[ 16%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.obj
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:20:0:
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:106:14: error: 'thread' in namespace 'std' does not name a type
         std::thread* thread;
              ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:115:14: error: 'mutex' in namespace 'std' does not name a type
         std::mutex sendQueueMutex;
              ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:117:14: error: 'mutex' in namespace 'std' does not name a type
         std::mutex receiveQueueMutex;
              ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h: In constructor 'Arcus::Socket::Private::Private()':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:82:15: error: class 'Arcus::Socket::Private' does not have any field named 'thread'
             , thread(nullptr)
               ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h: In member function 'void Arcus::Socket::Private::run()':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:251:21: error: 'sendQueueMutex' was not declared in this scope
                     sendQueueMutex.lock();
                     ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:280:25: error: 'sendQueueMutex' was not declared in this scope
                         sendQueueMutex.lock();
                         ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:312:25: error: 'sendQueueMutex' was not declared in this scope
                         sendQueueMutex.lock();
                         ^
In file included from E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:20:0:
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h: In member function 'void Arcus::Socket::Private::handleMessage(const std::shared_ptr<Arcus::Private::WireMessage>&)':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket_p.h:560:9: error: 'receiveQueueMutex' was not declared in this scope
         receiveQueueMutex.lock();
         ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In destructor 'virtual Arcus::Socket::~Socket()':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:32:11: error: 'class Arcus::Socket::Private' has no member named 'thread'
     if(d->thread)
           ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:38:19: error: 'class Arcus::Socket::Private' has no member named 'thread'
         delete d->thread;
                   ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In member function 'void Arcus::Socket::connect(const string&, int)':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:122:47: error: 'class Arcus::Socket::Private' has no member named 'thread'
     if(d->state != SocketState::Initial || d->thread != nullptr)
                                               ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:130:8: error: 'class Arcus::Socket::Private' has no member named 'thread'
     d->thread = new std::thread([&]() { d->run(); });
        ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:130:21: error: expected type-specifier
     d->thread = new std::thread([&]() { d->run(); });
                     ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:130:52: error: expected primary-expression before ')' token
     d->thread = new std::thread([&]() { d->run(); });
                                                    ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In member function 'void Arcus::Socket::reset()':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:142:11: error: 'class Arcus::Socket::Private' has no member named 'thread'
     if(d->thread)
           ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:144:12: error: 'class Arcus::Socket::Private' has no member named 'thread'
         d->thread->join();
            ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:145:12: error: 'class Arcus::Socket::Private' has no member named 'thread'
         d->thread = nullptr;
            ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In member function 'void Arcus::Socket::listen(const string&, int)':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:157:8: error: 'class Arcus::Socket::Private' has no member named 'thread'
     d->thread = new std::thread([&]() { d->run(); });
        ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:157:21: error: expected type-specifier
     d->thread = new std::thread([&]() { d->run(); });
                     ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:157:52: error: expected primary-expression before ')' token
     d->thread = new std::thread([&]() { d->run(); });
                                                    ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In member function 'void Arcus::Socket::close()':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:183:18: error: 'std::this_thread' has not been declared
             std::this_thread::sleep_for(std::chrono::milliseconds(100));
                  ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:196:11: error: 'class Arcus::Socket::Private' has no member named 'thread'
     if(d->thread)
           ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:198:12: error: 'class Arcus::Socket::Private' has no member named 'thread'
         d->thread->join();
            ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:199:19: error: 'class Arcus::Socket::Private' has no member named 'thread'
         delete d->thread;
                   ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:200:12: error: 'class Arcus::Socket::Private' has no member named 'thread'
         d->thread = nullptr;
            ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In member function 'void Arcus::Socket::sendMessage(Arcus::MessagePtr)':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:212:21: error: 'mutex' is not a member of 'std'
     std::lock_guard<std::mutex> lock(d->sendQueueMutex);
                     ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:212:21: error: 'mutex' is not a member of 'std'
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:212:31: error: template argument 1 is invalid
     std::lock_guard<std::mutex> lock(d->sendQueueMutex);
                               ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:212:41: error: 'class Arcus::Socket::Private' has no member named 'sendQueueMutex'
     std::lock_guard<std::mutex> lock(d->sendQueueMutex);
                                         ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp: In member function 'Arcus::MessagePtr Arcus::Socket::takeNextMessage()':
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:218:21: error: 'mutex' is not a member of 'std'
     std::lock_guard<std::mutex> lock(d->receiveQueueMutex);
                     ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:218:21: error: 'mutex' is not a member of 'std'
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:218:31: error: template argument 1 is invalid
     std::lock_guard<std::mutex> lock(d->receiveQueueMutex);
                               ^
E:\test\cura-build\build\Arcus-prefix\src\Arcus\src\Socket.cpp:218:41: error: 'class Arcus::Socket::Private' has no member named 'receiveQueueMutex'
     std::lock_guard<std::mutex> lock(d->receiveQueueMutex);
                                         ^
CMakeFiles\Arcus.dir\build.make:62: recipe for target 'CMakeFiles/Arcus.dir/src/Socket.cpp.obj' failed
mingw32-make[5]: *** [CMakeFiles/Arcus.dir/src/Socket.cpp.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/Arcus.dir/all' failed
mingw32-make[4]: *** [CMakeFiles/Arcus.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make[3]: *** [all] Error 2
CMakeFiles\Arcus.dir\build.make:110: recipe for target 'Arcus-prefix/src/Arcus-stamp/Arcus-build' failed
mingw32-make[2]: *** [Arcus-prefix/src/Arcus-stamp/Arcus-build] Error 2
CMakeFiles\Makefile2:164: recipe for target 'CMakeFiles/Arcus.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/Arcus.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

E:\test\cura-build\build>

**Comment by 18504141418** [comment] 2016-03-12 05:39
Maybe your mingw32-64 is wrong.Don't choose win32

**Comment by macaddr** [comment] 2016-03-12 10:38
I try reinstall mingw-w64 to

>  x86_64-4.9.3-posix-seh-rt_v4-rev1


 Everything was on the right track at that time until what happened.
`

> E:\test\cura-build\build>cmake -G "MinGW Makefiles" -DBUILD_64BIT:BOOL=ON ..
> .......
> E:\test\cura-build\build>mingw32-make
> ........
> -- Installing: E:/test/cura-build/build/inst/./arduino/dpinst64.exe
> [100%] Completed 'cura-binary-data'
> [100%] Built target cura-binary-data
> Scanning dependencies of target build_exe
> Running py2exe
> Traceback (most recent call last):
>   File "setup_win32.py", line 13, in <module>
>     import Arcus
> ImportError: No module named 'Arcus'
> CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
> mingw32-make[2]: *** [build_exe] Error 1
> CMakeFiles\Makefile2:526: recipe for target 'CMakeFiles/build_exe.dir/all' failed
> mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
> makefile:148: recipe for target 'all' failed
> mingw32-make: *** [all] Error 2
> 
> E:\test\cura-build\build>

help wanted

**Comment by 18504141418** [comment] 2016-03-14 01:06
@macaddr  the same as yours
maybe there is someting wrong with the PATHONPATH.
please have a look at [7](https://github.com/Ultimaker/cura-build/issues/7)

**Comment by Ghostkeeper** [comment] 2016-03-14 09:36
Rather, that is a duplicate of #43.

**Comment by 18504141418** [comment] 2016-03-15 09:18
@Ghostkeeper  Please tell me which kind of compiler I need :smiley:

**Comment by Ghostkeeper** [comment] 2016-03-15 10:11
You seem to have the correct compiler now. The error you are getting is in the last step of the process, the packaging step which turns all .py scripts into one executable with py2exe. The compiler is not involved in that step any more.

Ultimaker uses GCC 4.9.2 with Posix thread support for all builds we make except OSX.

On Windows that means using MinGW-w64. On Windows, we are currently seeing if Qt can be compiled properly with MSVC because of an upstream bug.

For OSX we use Clang. I don't know exactly which version but it is a recent one.

**Comment by macaddr** [comment] 2016-03-22 13:39
@Ghostkeeper 
Maybe I forget some dependencies

I tested many times,

**Comment by awhiemstra** [comment] 2016-03-22 16:01
Because your pythonpath is not correct. You need to run the env_win32/env_win64 batch file from your build directory so things are set up correctly. Unfortunately there is no way around that.

**Comment by macaddr** [comment] 2016-03-24 04:14
mingw32-make done
mingw32-make package done 
I checkout branch 15.10,and build succeeded.

after mingw32-make done
 copy arduino to directory cura-build
 and copy vcredist_x64.exe
then 
 mingw32-make package
------------------------------------------------------------
Could I DIY the UI？
I installed Qt Creator .
Please teach me how to do it.
(^人^)

**Comment by Ghostkeeper** [comment] 2016-03-24 10:15
You need to add the path to your Arcus python package (Arcus.pyd I think) in your PYTHONPATH environment variable. You can do that by calling `SET PYTHONPATH=%PYTHONPATH%;C:\path\to\libArcus\bin`

Normally it will install Arcus to your Program Files folder on Windows. It might also still be in the directory of your cura-build repository. The `env_win64.bat` file should automatically set your PYTHONPATH environment variable correctly.

**Comment by sinnnnna** [comment] 2016-08-11 22:22
HI,
I still face this issue when I am trying to build cura. (I followed the instructions in cura-build)

---------------------------------
.
.
.
Traceback (most recent call last):
  File "setup_win32.py", line 13, in <module>
    import Arcus
ImportError: No module named 'Arcus'
CMakeFiles\build_exe.dir\build.make:56: recipe for target 'build_exe' failed
mingw32-make[2]: *** [build_exe] Error 1
CMakeFiles\Makefile2:563: recipe for target 'CMakeFiles/build_exe.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/build_exe.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

---------------------------------------------------

My system info:
Windows 10 64 bit
x86_64-4.9.3-posix-seh-rt_v4-rev1
Python Python 3.4.3 :: Anaconda 2.3.0 (64-bit)

PYTHONPATH-> not set because there is no "libArcus/bin folder"

**Comment by maarstra** [comment] 2017-01-07 10:11
Change 'Arcus' to 'arcus' in setup_win32.py or change the installation folder name from 'arcus' to 'Arcus'. Python is case-sensitive

**Comment by macaddr** [comment] 2017-01-18 02:44
@sinnnnna 
You need to add the path to your Arcus python package (Arcus.pyd I think) in your PYTHONPATH environment variable.

**Comment by LipuFei** [comment] 2019-08-13 12:38
Closing this issue due to inactivity.

**Closed by LipuFei** 2019-08-13 12:38 UTC
