### ISSUE TITLE
ubuntu-15.04-build-script.sh not mentioned in readme

### ISSUE THREAD

**Issue by peteruithoven** [Ultimaker/cura-build#37] opened 2016-02-18 14:51 UTC
What's the recommended way to build Cura on Ubuntu (Linux)? There is the `ubuntu-15.04-build-script.sh` script, but it isn't mentioned in the readme?

**Comment by LipuFei** [comment] 2019-08-09 11:44
The README has been updated, and you could also try using the docker images.

This is a duplicate of #36. I'll close this one.

**Closed by LipuFei** 2019-08-09 11:44 UTC
Labels: duplicate, help wanted
