### ISSUE TITLE
Cura build in Windows

### ISSUE THREAD

**Issue by rulochaparro** [Ultimaker/cura-build#145] opened 2017-11-28 15:57 UTC
Hi everyone, sorry if this problem have resolved in otrher issue but i dont find it. Im new in this and i was trying to get my version of cura. 
When i was in the terminal od windows doing the steps i get this error.:

CMake Error at CMakeLists.txt:23 (get_filename_component):
  get_filename_component unknown component CACHE

-- Found PythonInterp: C:/Users/Producto/AppData/Local/Programs/Python/Python35/
python.exe (found suitable version "3.5", minimum required is "3.5.0")
-- Found PyQt: C:/Users/Producto/AppData/Local/Programs/Python/Python35/lib/site
-packages/PyQt5 (found suitable version "5.9.1", minimum required is "5.6")
-- Found SciPy: C:/Users/Producto/AppData/Local/Programs/Python/Python35/lib/sit
e-packages/scipy (found suitable version "1.0.0", minimum required is "0.17")
-- Found cx_Freeze: C:/Users/Producto/AppData/Local/Programs/Python/Python35/lib
/site-packages/cx_Freeze (found version "6.0b1")
-- Found Signtool: C:/Users/Producto/AppData/Local/Programs/Python/Python35/Scri
pts/signtool.exe
CMake Error at signing/windows.cmake:16 (message):
  You can't sign your executables without passing your password here!
Call Stack (most recent call first):
  CMakeLists.txt:87 (include)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Producto/Documents/GitHub/cura-build/build/CMakeFiles/CMakeOu
tput.log".

can someone helpme? Thank you!!

**Comment by thopiekar** [comment] 2017-11-28 16:03
Just skip signing.. See CMakeLists.txt.

**Comment by rulochaparro** [comment] 2017-11-28 16:42
Thank you for your answer. do you mean that i have to comment the part of sign packages on CMakeLists.txt ?? Whatut about this? CMake Error at CMakeLists.txt:23 (get_filename_component):
get_filename_component unknown component CACHE

**Comment by thopiekar** [comment] 2017-11-28 16:44
Nope, you need to set an option when building and calling cmake..
Just add the option like I did: (This is from my build script which is able to produce an NSIS installer at the end..)
```
cmake %CURA_BUILD_SOURCE% -DSIGN_PACKAGE:BOOL=OFF [...]
```

**Comment by thopiekar** [comment] 2017-11-28 17:03
Either type it into your command line manually or use a batch file.
`%CURA_BUILD_SOURCE%` is here a variable which is pointing at the source directory of cura-build.

**Comment by carlosdeperini** [comment] 2017-11-30 13:47
Hi Rulo, I´ve the same problem with the CACHE.  But I´ve other mistake, my console show me:

CMake Error at CMakeLists.txt:23 (get_filename_component):
  get_filename_component unknown component CACHE

I followed the steps of @thopiekar but I can´t solved the problem. Any sugest??

**Comment by thopiekar** [comment] 2017-11-30 13:59
Hey dudes..

there is nothing wrong with your cache or whatever.
I wrote this piece of code about one year before. What you see is a warning.

On Windows you need to sign executables with a signature. Otherwise you get a warning from Windows about running a executable, which is unsigned. In some cases depending on setups in companies, they don't allow to run unsigned applications.

What the warning is telling you, is that you should pass a sign key and the password OR, as I suggested before, turn off to sign your executable.

If you are using these build tools for the first time, please google around and read into how to use build tools and how to set options on a command line application.
I also had to learn about these things years before. So take your time, if you haven't did that before.

**Comment by Ghostkeeper** [comment] 2017-12-13 10:42
Seems to be a duplicate of https://github.com/Ultimaker/cura-build/issues/109

**Comment by Shaische** [comment] 2017-12-25 05:24
I just opened a new issue related to this. I think Cura's build notes are outdated. Can someone please update the instructions!?

**Comment by Ghostkeeper** [comment] 2018-01-15 16:24
I've updated the instructions.

**Comment by woshisuchao** [comment] 2018-01-23 05:30
@thopiekar  i also come with these problem , did you mean :
![image](https://user-images.githubusercontent.com/31384654/35259575-9e6eb1e8-0041-11e8-8d1d-cff2ef1b6400.png)

im newer , please help detail

**Comment by woshisuchao** [comment] 2018-01-23 06:53
![image](https://user-images.githubusercontent.com/31384654/35261883-1d33f438-004d-11e8-9a5f-70638debecb6.png)

**Comment by woshisuchao** [comment] 2018-01-23 08:07
![image](https://user-images.githubusercontent.com/31384654/35264358-71191e7a-0057-11e8-9ffe-f8e1abb7d8fd.png)
this or
![image](https://user-images.githubusercontent.com/31384654/35264373-80edc2c4-0057-11e8-98c6-d123454e810a.png)
or this
![image](https://user-images.githubusercontent.com/31384654/35264385-8bf83762-0057-11e8-9350-193f582d2260.png)
 help...

**Comment by woshisuchao** [comment] 2018-01-23 09:01
![image](https://user-images.githubusercontent.com/31384654/35266715-0ab401e2-005f-11e8-8e56-c9e4578b4471.png)
->
![image](https://user-images.githubusercontent.com/31384654/35266727-158f0134-005f-11e8-8e75-0bafe51221d6.png)

**Comment by LipuFei** [comment] 2019-08-09 11:14
The original question has been answered. I'll close this issue due to inactivity.

**Closed by LipuFei** 2019-08-09 11:14 UTC
Labels: help wanted
